lista = [2, 4, 7, 2, 3, 3, 1, 0, 2, 6]
lista2 = []
lista.count(0)
lista2.append(lista.count(0))
lista.count(1)
lista2.append(lista.count(1))
lista.count(2)
lista2.append(lista.count(2))
lista.count(3)
lista2.append(lista.count(3))
lista.count(4)
lista2.append(lista.count(4))
lista.count(6)
lista2.append(lista.count(6))
lista.count(7)
lista2.append(lista.count(7))
print(lista2)
lista.index(lista2)
print(max(lista2))  